server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/simple_doc_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 39355448136-tkbj6j2g8n57fkn2h3uen87g833fjvjh.apps.googleusercontent.com
            clientSecret: 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
