server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: "jdbc:mysql://s15.infinitysrv.com:3306/simpledo_doc_db"
    username:  "simpledo_adm"
    password: "}1$&{w6V}wPn"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "39355448136-tkbj6j2g8n57fkn2h3uen87g833fjvjh.apps.googleusercontent.com"
            clientSecret: "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"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200KB
      max-request-size: 200MB
